# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.22.17-standalone/deployment-apps-v1.json

apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app.kubernetes.io/component: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: worker
          image: ocsarchive-iiif-backend
          command:
            - python
            - -m
            - ocsarchive_iiif.temporal.worker
          envFrom:
            - configMapRef:
                name: common-env
                optional: false
            - configMapRef:
                name: worker-env
                optional: false
          volumeMounts:
            - name: working-dir
              mountPath: /mnt/volumes/working-dir
      volumes:
        - name: working-dir
          ephemeral:
            volumeClaimTemplate:
              metadata:
                labels:
                  app.kubernetes.io/component: worker
              spec:
                accessModes:
                  - "ReadWriteOnce"
                resources:
                  requests:
                    storage: 1Gi
